// data.js —— 题库（Unicode 下标版本）
export const compounds = [
  { key: "H2O",   name: "Water",                 formula: "H₂O" },
  { key: "CO2",   name: "Carbon dioxide",        formula: "CO₂" },
  { key: "O2",    name: "Oxygen",                formula: "O₂" },
  { key: "N2",    name: "Nitrogen",              formula: "N₂" },
  { key: "O3",    name: "Ozone",                 formula: "O₃" },
  { key: "NH3",   name: "Ammonia",               formula: "NH₃" },
  { key: "CH4",   name: "Methane",               formula: "CH₄" },
  { key: "H2SO4", name: "Sulfuric acid",         formula: "H₂SO₄" },
  { key: "NaCl",  name: "Sodium chloride",       formula: "NaCl" },
  { key: "NaOH",  name: "Sodium hydroxide",      formula: "NaOH" },
  { key: "HCl",   name: "Hydrochloric acid",     formula: "HCl" },
  { key: "C6H12O6", name: "Glucose",             formula: "C₆H₁₂O₆" },
  { key: "C12H22O11", name:"Sucrose",            formula: "C₁₂H₂₂O₁₁" },
  { key: "C2H5OH",  name: "Ethanol",             formula: "C₂H₅OH" },
  { key: "CaCO3",   name: "Calcium carbonate",   formula: "CaCO₃" },
  { key: "HNO3",    name: "Nitric acid",         formula: "HNO₃" },
  { key: "NaHCO3",  name: "Sodium bicarbonate",  formula: "NaHCO₃" },
  { key: "Ca(OH)2", name: "Calcium hydroxide",   formula: "Ca(OH)₂" },
  { key: "MgSO4",   name: "Magnesium sulfate",   formula: "MgSO₄" },
  { key: "CuSO4",   name: "Copper(II) sulfate",  formula: "CuSO₄" },
  { key: "Na2CO3",  name: "Sodium carbonate",    formula: "Na₂CO₃" },
  { key: "H3PO4",   name: "Phosphoric acid",     formula: "H₃PO₄" },
  { key: "H2O2",    name: "Hydrogen peroxide",   formula: "H₂O₂" },
  { key: "NaClO",   name: "Sodium hypochlorite", formula: "NaClO" },
  { key: "NH4NO3",  name: "Ammonium nitrate",    formula: "NH₄NO₃" },
  { key: "CaCl2",   name: "Calcium chloride",    formula: "CaCl₂" },
  { key: "KMnO4",   name: "Potassium permanganate", formula: "KMnO₄" },
  { key: "Na2SO4",  name: "Sodium sulfate",      formula: "Na₂SO₄" },
  { key: "SiO2",    name: "Silicon dioxide",     formula: "SiO₂" },
  { key: "Al2O3",   name: "Aluminum oxide",      formula: "Al₂O₃" },
  { key: "Ca3(PO4)2", name: "Calcium phosphate", formula: "Ca₃(PO₄)₂" },
  { key: "NaNO3",   name: "Sodium nitrate",      formula: "NaNO₃" },
  { key: "KCl",     name: "Potassium chloride",  formula: "KCl" },
  { key: "MgO",     name: "Magnesium oxide",     formula: "MgO" },
  { key: "CH3COOH", name: "Acetic acid",         formula: "CH₃COOH" },
  { key: "CH3COONa",name: "Sodium acetate",      formula: "CH₃COONa" },
  { key: "NH4Cl",   name: "Ammonium chloride",   formula: "NH₄Cl" },
  { key: "CaSO4",   name: "Calcium sulfate",     formula: "CaSO₄" }
];
